CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS spatial;
CREATE SCHEMA IF NOT EXISTS metrics;

ALTER SCHEMA core OWNER TO sc_user;
ALTER SCHEMA spatial OWNER TO sc_user;
ALTER SCHEMA metrics OWNER TO sc_user;

